"""Added Foreign Key

Revision ID: 788e7a5c3415
Revises: 5d21fa233911
Create Date: 2024-10-09 09:52:01.683834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788e7a5c3415'
down_revision = '5d21fa233911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_posts_poster_id_users', 'users', ['poster_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_posts_poster_id_users', type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
