"""password_hash

Revision ID: 87933471e2d7
Revises: fb6a6e76dd91
Create Date: 2024-10-07 18:38:07.272754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87933471e2d7'
down_revision = 'fb6a6e76dd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.drop_column('check_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
