"""added password field

Revision ID: fb6a6e76dd91
Revises: cd97a0d967e9
Create Date: 2024-10-07 18:10:20.994309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6a6e76dd91'
down_revision = 'cd97a0d967e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('check_password_hash')

    # ### end Alembic commands ###
